name: Release

on:
  push:
    paths-ignore: ["**.md", "LICENSE", ".github/dependabot.yml"]
    branches: ["master", "main"]
  schedule:
    - cron: "5 4 * * 2"
  workflow_dispatch:

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 #v4.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0
            @semantic-release/github@10.1.1
