name: Release

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".github/dependabot.yml"
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
    types:
      - closed
  schedule:
    - cron: "5 4 1 * *"
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged != false
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.7.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
